// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCusS3jhWeaPbXfyJV2Oin1cid4oyBDdrI',
    appId: '1:89322291997:web:3091550a4592f0dab997f4',
    messagingSenderId: '89322291997',
    projectId: 'law-genie-56982041-cd466',
    authDomain: 'law-genie-56982041-cd466.firebaseapp.com',
    databaseURL: 'https://law-genie-56982041-cd466-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'law-genie-56982041-cd466.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCoyidK52lnKfDQSoA3kBJHP66aRoF7iI',
    appId: '1:89322291997:android:62dba2028e984884b997f4',
    messagingSenderId: '89322291997',
    projectId: 'law-genie-56982041-cd466',
    databaseURL: 'https://law-genie-56982041-cd466-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'law-genie-56982041-cd466.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEKq4A0ETR0EjufjQ_A1eAwooMsTew84o',
    appId: '1:89322291997:ios:3e6887d449e0e49eb997f4',
    messagingSenderId: '89322291997',
    projectId: 'law-genie-56982041-cd466',
    databaseURL: 'https://law-genie-56982041-cd466-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'law-genie-56982041-cd466.firebasestorage.app',
    androidClientId: '89322291997-3jpqinq9oqo52fjuf1qqn57tf5j25765.apps.googleusercontent.com',
    iosClientId: '89322291997-gits7uhcft2s2n4jl956p1krnmp7p27f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

}