import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:iconsax/iconsax.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class DocumentViewerPage extends StatefulWidget {
  final String documentContent;

  const DocumentViewerPage({super.key, required this.documentContent});

  @override
  State<DocumentViewerPage> createState() => _DocumentViewerPageState();
}

class _DocumentViewerPageState extends State<DocumentViewerPage> {
  bool _isDownloading = false;

  Future<Uint8List> _generatePdf() async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.poppinsRegular();
    final boldFont = await PdfGoogleFonts.poppinsBold();
    // Load logo image from assets
    final logoImage = await imageFromAssetBundle('assets/images/logo.png');

    // Add cover page with logo and branding
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Column(
              mainAxisAlignment: pw.MainAxisAlignment.center,
              children: [
                pw.ClipRRect(
                  horizontalRadius: 12,
                  verticalRadius: 12,
                  child: pw.Image(logoImage, width: 120, height: 120),
                ),
                pw.SizedBox(height: 30),
                pw.Text(
                  'Law Genie',
                  style: pw.TextStyle(
                    font: boldFont,
                    fontSize: 36,
                    color: PdfColors.blue800,
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Text(
                  'Your AI Legal Assistant',
                  style: pw.TextStyle(
                    font: font,
                    fontSize: 16,
                    color: PdfColors.grey700,
                  ),
                ),
                pw.SizedBox(height: 50),
                pw.Divider(color: PdfColors.grey400, thickness: 2),
                pw.SizedBox(height: 20),
                pw.Text(
                  'Generated Document',
                  style: pw.TextStyle(
                    font: boldFont,
                    fontSize: 20,
                    color: PdfColors.grey800,
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Text(
                  'Date: ${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}',
                  style: pw.TextStyle(
                    font: font,
                    fontSize: 12,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );

    // Add content pages with header and footer
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        header: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(bottom: 20.0),
            padding: const pw.EdgeInsets.only(bottom: 10.0),
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                  bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5)),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Law Genie',
                    style: pw.TextStyle(
                        font: boldFont,
                        fontSize: 14,
                        color: PdfColors.blue800)),
                pw.ClipRRect(
                  horizontalRadius: 8,
                  verticalRadius: 8,
                  child: pw.Image(logoImage, width: 30, height: 30),
                ),
              ],
            ),
          );
        },
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.center,
            margin: const pw.EdgeInsets.only(top: 20.0),
            child: pw.Column(
              children: [
                pw.Divider(color: PdfColors.grey300),
                pw.SizedBox(height: 5),
                pw.Text('Generated by Law Genie - Your AI Legal Assistant',
                    style: pw.TextStyle(
                        font: font, fontSize: 10, color: PdfColors.grey600)),
                pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
                    style: pw.TextStyle(
                        font: font, fontSize: 10, color: PdfColors.grey600)),
              ],
            ),
          );
        },
        build: (pw.Context context) {
          // Split content into lines for proper pagination
          return widget.documentContent
              .split('\n')
              .map((line) => pw.Container(
                    margin: const pw.EdgeInsets.only(bottom: 5),
                    child: pw.Text(line,
                        style: pw.TextStyle(font: font, fontSize: 12)),
                  ))
              .toList();
        },
      ),
    );
    return pdf.save();
  }

  Future<void> _sharePdf() async {
    setState(() => _isDownloading = true);
    try {
      final pdfData = await _generatePdf();
      final fileName =
          'LawGenie_Doc_${DateTime.now().millisecondsSinceEpoch}.pdf';
      await Printing.sharePdf(bytes: pdfData, filename: fileName);
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error sharing PDF: $e')),
      );
    } finally {
      setState(() => _isDownloading = false);
    }
  }

  Future<void> _downloadPdf() async {
    setState(() => _isDownloading = true);
    try {
      final pdfData = await _generatePdf();
      final fileName =
          'LawGenie_Doc_${DateTime.now().millisecondsSinceEpoch}.pdf';

      // On Android, try to save to Downloads. On iOS, Share is the way.
      // For simplicity and reliability, we'll use Printing.layoutPdf for "Download"
      // which opens the print preview where "Save as PDF" is a primary option.
      // OR we can just use sharePdf again but user asked for separate options.
      // Let's try to be smart: Share = Share Sheet. Download = LayoutPdf (Print/Save).

      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdfData,
        name: fileName,
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error downloading PDF: $e')),
      );
    } finally {
      setState(() => _isDownloading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0A032A), // Dark background
      appBar: AppBar(
        backgroundColor: const Color(0xFF2C55A9), // Match app primary color
        elevation: 1,
        shadowColor: Colors.black.withOpacity(0.3),
        leading: IconButton(
          icon: const Icon(Iconsax.arrow_left, color: Colors.white),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Generated Document',
          style: GoogleFonts.merriweather(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 20,
          ),
        ),
        actions: [
          if (_isDownloading)
            const Padding(
              padding: EdgeInsets.only(right: 16.0),
              child: SizedBox(
                width: 24,
                height: 24,
                child: CircularProgressIndicator(
                    strokeWidth: 2.5, color: Color(0xFF4A8CFF)),
              ),
            )
          else ...[
            IconButton(
              icon: const Icon(Iconsax.document_download, color: Colors.white),
              onPressed: _downloadPdf,
              tooltip: 'Download PDF',
            ),
            IconButton(
              icon: const Icon(Iconsax.share, color: Colors.white),
              onPressed: _sharePdf,
              tooltip: 'Share PDF',
            ),
          ]
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Container(
          padding: const EdgeInsets.all(24.0),
          decoration: BoxDecoration(
            color: const Color(0xFF19173A), // Dark card background
            borderRadius: BorderRadius.circular(12.0),
            border: Border.all(color: const Color(0xFF2C55A9), width: 1),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // UI Preview Branding
              Center(
                child: Column(
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(
                          16.0), // Rounded corners for logo
                      child: Image.asset('assets/images/logo.png',
                          width: 80, height: 80),
                    ),
                    const SizedBox(height: 10),
                    ShaderMask(
                      shaderCallback: (bounds) => const LinearGradient(
                        colors: [
                          Color(0xFF1565C0), // Dark Blue
                          Color(0xFF42A5F5), // Light Blue
                        ],
                        begin: Alignment.topLeft,
                        end: Alignment.bottomRight,
                      ).createShader(bounds),
                      child: Text(
                        'Law Genie',
                        style: GoogleFonts.poppins(
                          fontSize: 24,
                          fontWeight: FontWeight.bold,
                          color: Colors.white, // Required for ShaderMask
                        ),
                      ),
                    ),
                    Text(
                      'Document Generator',
                      style: GoogleFonts.poppins(
                        fontSize: 14,
                        color: Colors.white70, // Light text for dark background
                      ),
                    ),
                    const SizedBox(height: 20),
                    const Divider(),
                    const SizedBox(height: 20),
                  ],
                ),
              ),
              // Document Content
              SelectableText(
                widget.documentContent,
                style: GoogleFonts.poppins(
                  fontSize: 14,
                  color: Colors.white, // White text for dark background
                  height: 1.6,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
