
const Map<String, List<String>> documentFields = {
  'Select Document Type': [],
  '✍️ Affidavit': [
    'Deponent Name',
    'Deponent Address',
    'Date of Affidavit',
    'Place of Affidavit',
    'Statement of Facts',
    'Additional Details (Optional)',
  ],
  '🤝 Agreement for Sale': [
    'Seller Name',
    'Seller Address',
    'Buyer Name',
    'Buyer Address',
    'Property Description',
    'Total Sale Consideration',
    'Advance Amount Paid',
    'Additional Details (Optional)',
  ],
   '🤝 Agreement to Sell': [
    'Seller Name',
    'Seller Address',
    'Buyer Name',
    'Buyer Address',
    'Property Description',
    'Total Sale Consideration',
    'Advance Amount Paid',
    'Additional Details (Optional)',
  ],
  '⚖️ Bail Application': [
    'Accused Name',
    'Case FIR No.',
    'Police Station',
    'Section of Law',
    'Date of Arrest',
    'Grounds for Bail',
    'Additional Details (Optional)',
  ],
  '✉️ Cheque Bounce Notice': [
    'Drawer Name (Issuer of Cheque)',
    'Drawer Address',
    'Payee Name (Receiver of Cheque)',
    'Cheque Number',
    'Cheque Date',
    'Cheque Amount',
    'Reason for Dishonor',
    'Additional Details (Optional)',
  ],
  '👨‍👩‍👧 Child Custody Agreement': [
    'Parent 1 Name',
    'Parent 2 Name',
    'Child(ren)\'s Name(s) and Date(s) of Birth',
    'Physical Custody Arrangement',
    'Legal Custody Arrangement',
    'Visitation Schedule',
    'Additional Details (Optional)',
  ],
   '🏢 Company HR Policies': [
    'Company Name',
    'Policy Title (e.g., Leave Policy, Code of Conduct)',
    'Effective Date',
    'Policy Details',
    'Additional Details (Optional)',
  ],
  '🛒 Consumer Complaint': [
    'Complainant Name',
    'Complainant Address',
    'Opposite Party Name',
    'Opposite Party Address',
    'Details of Goods/Service',
    'Defect/Deficiency in Service',
    'Relief Claimed',
    'Additional Details (Optional)',
  ],
  '💔 Divorce Petition': [
    'Petitioner Name',
    'Respondent Name',
    'Date of Marriage',
    'Place of Marriage',
    'Grounds for Divorce',
    'Additional Details (Optional)',
  ],
   '📦 Distributor Agreement': [
    'Supplier/Manufacturer Name',
    'Distributor Name',
    'Territory',
    'Products Covered',
    'Term of Agreement',
    'Sales and Marketing Obligations',
    'Additional Details (Optional)',
  ],
  '✍️ Durable Power of Attorney': [
    'Principal Name',
    'Principal Address',
    'Agent Name',
    'Agent Address',
    'Powers Granted',
    'Effective Date',
    'Additional Details (Optional)',
  ],
   '🚨 FIR Draft': [
    'Informant\'s Name and Address',
    'Date and Time of Offence',
    'Place of Offence',
    'Description of the Accused (if known)',
    'Detailed account of the incident/offence',
    'List of Stolen/Lost items (if applicable)',
    'Witnesses (if any)',
    'Additional Details (Optional)',
  ],
  '🤝 Franchise Agreement': [
    'Franchisor Name',
    'Franchisee Name',
    'Franchise Territory',
    'Franchise Fee',
    'Royalty Percentage',
    'Term of Agreement',
    'Additional Details (Optional)',
  ],
  '🎁 Gift Deed': [
    'Donor Name',
    'Donor Address',
    'Donee Name',
    'Donee Address',
    'Property Description',
    'Date of Gift',
    'Additional Details (Optional)',
  ],
  '🛡️ Indemnity Bond': [
    'Indemnifier Name',
    'Indemnity Holder Name',
    'Contract/Agreement Reference',
    'Indemnified Amount',
    'Purpose of Indemnity',
    'Additional Details (Optional)',
  ],
  '🤝 Joint Venture Agreement': [
    'Party A Name',
    'Party B Name',
    'Venture Name',
    'Purpose of Venture',
    'Initial Capital Contribution by Party A',
    'Initial Capital Contribution by Party B',
    'Additional Details (Optional)',
  ],
  '📄 Lease Agreement': [
    'Lessor (Landlord) Name',
    'Lessee (Tenant) Name',
    'Leased Property Address',
    'Lease Term (in years)',
    'Rent Amount per Month',
    'Security Deposit',
    'Additional Details (Optional)',
  ],
  '⚖️ Legal Notice': [
    'Sender Name',
    'Sender Address',
    'Recipient Name',
    'Recipient Address',
    'Subject',
    'Detailed Grievance',
    'Relief Sought',
    'Additional Details (Optional)',
  ],
  '📜 Licensing Agreement': [
    'Licensor Name',
    'Licensee Name',
    'Licensed Property (e.g., trademark, copyright, patent)',
    'Scope of License (e.g., territory, duration)',
    'License Fee/Royalty',
    'Additional Details (Optional)',
  ],
  '📝 Living Will': [
    'Declarant Name',
    'Declarant Address',
    'Healthcare Agent Name',
    'End-of-Life Care Wishes',
    'Additional Details (Optional)',
  ],
   '💰 Loan Agreement': [
    'Lender Name',
    'Borrower Name',
    'Loan Amount',
    'Interest Rate',
    'Repayment Schedule',
    'Additional Details (Optional)',
  ],
  '🏠 Mortgage Agreement': [
    'Mortgagor (Borrower) Name',
    'Mortgagee (Lender) Name',
    'Loan Amount',
    'Property Details for Mortgage',
    'Additional Details (Optional)',
  ],
  '🏠 Mortgage Deed': [
    'Mortgagor (Borrower) Name',
    'Mortgagee (Lender) Name',
    'Loan Amount',
    'Property Details for Mortgage',
    'Additional Details (Optional)',
  ],
  '🤫 Non-Disclosure Agreement (NDA)': [
    'Disclosing Party Name',
    'Receiving Party Name',
    'Confidential Information Description',
    'Term of NDA',
    'Additional Details (Optional)',
  ],
   '💌 Offer Letter': [
    'Company Name',
    'Candidate Name',
    'Job Title',
    'Salary/Stipend',
    'Start Date',
    'Reporting Manager',
    'Work Location',
    'Additional Details (Optional)',
  ],
  '🧑‍🤝‍🧑 Partnership Deed': [
    'Partner 1 Name',
    'Partner 1 Address',
    'Partner 2 Name',
    'Partner 2 Address',
    'Business Name',
    'Business Address',
    'Capital Contribution by Partner 1',
    'Capital Contribution by Partner 2',
    'Profit/Loss Sharing Ratio',
    'Additional Details (Optional)',
  ],
   '✍️ Power of Attorney': [
    'Principal Name',
    'Principal Address',
    'Agent (Attorney-in-Fact) Name',
    'Agent Address',
    'Powers Granted',
    'Date of Execution',
    'Place of Execution',
    'Additional Details (Optional)',
  ],
  '🔒 Privacy Policy': [
    'Website/App Name',
    'Types of Data Collected',
    'Purpose of Data Collection',
    'Data Sharing and Disclosure',
    'User Rights',
    'Additional Details (Optional)',
  ],
   '📝 Promissory Note': [
    'Maker (Borrower) Name',
    'Payee (Lender) Name',
    'Principal Amount',
    'Interest Rate (if any)',
    'Date of Note',
    'Maturity Date',
    'Additional Details (Optional)',
  ],
  '🏠 Rent Agreement': [
    'Landlord Name',
    'Landlord Address',
    'Tenant Name',
    'Tenant Address',
    'Property Address',
    'Rent Amount',
    'Lease Term (in months)',
    'Security Deposit',
    'Additional Details (Optional)',
  ],
  '📄 Sale Deed': [
    'Vendor Name',
    'Vendor Address',
    'Vendee Name',
    'Vendee Address',
    'Property Description',
    'Sale Amount',
    'Witness 1 Name',
    'Witness 2 Name',
    'Additional Details (Optional)',
  ],
  '🚚 Supply Agreement': [
    'Supplier Name',
    'Customer Name',
    'Description of Goods',
    'Price and Payment Terms',
    'Delivery Schedule',
    'Additional Details (Optional)',
  ],
  '🚫 Termination Letter': [
    'Employee Name',
    'Employee ID',
    'Company Name',
    'Termination Date',
    'Reason for Termination',
    'Additional Details (Optional)',
  ],
  '🚗 Vehicle Insurance Transfer Request Letter': [
    'Policy Holder\'s Name (Seller)',
    'Insurance Company Name',
    'Policy Number',
    'Vehicle Registration Number',
    'New Owner\'s Name (Buyer)',
    'Date of Vehicle Sale',
    'Additional Details (Optional)',
  ],
  '🚗 Vehicle Purchase Agreement': [
    'Buyer Name',
    'Seller Name',
    'Vehicle Details (Make, Model, VIN)',
    'Purchase Price',
    'Payment Method',
    'Date of Purchase',
    'Additional Details (Optional)',
  ],
  '🚗 Vehicle Sale Agreement': [
    'Seller Name',
    'Buyer Name',
    'Vehicle Make',
    'Vehicle Model',
    'Vehicle Year',
    'VIN (Vehicle Identification Number)',
    'Sale Price',
    'Date of Sale',
    'Additional Details (Optional)',
  ],
  '🚗 Vehicle Transfer of Ownership Undertaking': [
    'Seller/Transferor Name',
    'Buyer/Transferee Name',
    'Vehicle Registration Number',
    'Vehicle Make and Model',
    'Date of Transfer',
    'Declaration of transfer of all rights and liabilities',
    'Additional Details (Optional)',
  ],
  '📝 Will': [
    'Testator Name',
    'Testator Address',
    'Executor Name',
    'Executor Address',
    'Beneficiary Name',
    'Beneficiary Relationship',
    'Asset Details',
    'Additional Details (Optional)',
  ],
  '👨‍👩‍👧 Adoption Deed': [
    'Adoptive Father\'s Name',
    'Adoptive Mother\'s Name',
    'Biological Father\'s Name',
    'Biological Mother\'s Name',
    'Child\'s Name',
    'Date of Adoption',
    'Additional Details (Optional)',
  ],
  '⚖️ Arbitration Agreement': [
    'Party 1 Name',
    'Party 2 Name',
    'Subject of Dispute',
    'Seat of Arbitration',
    'Additional Details (Optional)',
  ],
  '✍️ Assignment Deed': [
    'Assignor Name',
    'Assignee Name',
    'Asset/Right to be Assigned',
    'Consideration Amount',
    'Additional Details (Optional)',
  ],
  '🧑‍🤝‍🧑 Co-founder\'s Agreement': [
    'Founder 1 Name',
    'Founder 2 Name',
    'Company Name',
    'Equity Split',
    'Roles and Responsibilities',
    'Additional Details (Optional)',
  ],
  '🧑‍🏫 Consultancy Agreement': [
    'Consultant Name',
    'Client Name',
    'Services to be Provided',
    'Consultation Fee',
    'Additional Details (Optional)',
  ],
  '🛠️ Contract for Services': [
    'Service Provider Name',
    'Client Name',
    'Description of Services',
    'Payment Terms',
    'Additional Details (Optional)',
  ],
  '🤝 Memorandum of Understanding (MoU)': [
    'Party 1 Name',
    'Party 2 Name',
    'Purpose of MoU',
    'Key Responsibilities of Parties',
    'Additional Details (Optional)',
  ],
  '👍 No Objection Certificate (NOC)': [
    'Issuer Name',
    'Recipient Name',
    'Purpose of NOC',
    'Details of Property/Item',
    'Additional Details (Optional)',
  ],
  '🌐 Website Privacy Policy': [
    'Website URL',
    'Types of Data Collected',
    'Purpose of Data Collection',
    'Data Storage and Security Measures',
    'Additional Details (Optional)',
  ],
  '📜 Website Terms and Conditions': [
    'Website URL',
    'User Responsibilities',
    'Disclaimers',
    'Governing Law',
    'Additional Details (Optional)',
  ],
  '📄 Plaint': [
    'Plaintiff Name',
    'Plaintiff Address',
    'Defendant Name',
    'Defendant Address',
    'Cause of Action',
    'Relief Claimed',
    'Additional Details (Optional)',
  ],
  '📄 Written Statement': [
    'Defendant Name',
    'Defendant Address',
    'Plaintiff Name',
    'Plaintiff Address',
    'Response to Plaint',
    'Additional Details (Optional)',
  ],
  '🔄 Revision Petition': [
    'Petitioner Name',
    'Respondent Name',
    'Order under Revision',
    'Grounds for Revision',
    'Additional Details (Optional)',
  ],
  '🔼 Appeal Petition': [
    'Appellant Name',
    'Respondent Name',
    'Order under Appeal',
    'Grounds for Appeal',
    'Additional Details (Optional)',
  ],
  '👨‍💻 Internship/ Service Contract Draft': [
    'Intern/Employee Name',
    'Company Name',
    'Job Title/Internship Role',
    'Stipend/Salary',
    'Start Date',
    'End Date',
    'Additional Details (Optional)',
  ],
  '✍️ Undertaking': [
    'Name of Person giving Undertaking',
    'Address',
    'Details of Undertaking',
    'Date',
    'Additional Details (Optional)',
  ],
  '💡 Letter of Intent (LOI)': [
    'Sender Name',
    'Recipient Name',
    'Purpose of LOI',
    'Key Terms of Proposed Agreement',
    'Additional Details (Optional)',
  ],
  '⏳ Interlocutory Application (IA)': [
    'Applicant Name',
    'Respondent Name',
    'Main Case Number',
    'Prayer in IA',
    'Additional Details (Optional)',
  ],
  '🚫 Injunction Application': [
    'Applicant Name',
    'Respondent Name',
    'Main Case Number',
    'Urgent Grounds for Injunction',
    'Additional Details (Optional)',
  ],
  '💰 Maintenance Petition': [
    'Petitioner Name',
    'Respondent Name',
    'Grounds for Maintenance',
    'Amount of Maintenance Claimed',
    'Additional Details (Optional)',
  ],
  'ℹ️ RTI Application': [
    'Applicant Name',
    'Applicant Address',
    'Public Information Officer (PIO) Name',
    'PIO Address',
    'Information Requested',
    'Additional Details (Optional)',
  ]
};
