
const Map<String, List<String>> documentFields = {
  'Select Document Type': [],
  'Affidavit': [
    'Deponent Name',
    'Deponent Address',
    'Date of Affidavit',
    'Place of Affidavit',
    'Statement of Facts',
  ],
  'Agreement for Sale': [
    'Seller Name',
    'Seller Address',
    'Buyer Name',
    'Buyer Address',
    'Property Description',
    'Total Sale Consideration',
    'Advance Amount Paid',
  ],
  'Bail Application': [
    'Accused Name',
    'Case FIR No.',
    'Police Station',
    'Section of Law',
    'Date of Arrest',
    'Grounds for Bail',
  ],
  'Cheque Bounce Notice': [
    'Drawer Name (Issuer of Cheque)',
    'Drawer Address',
    'Payee Name (Receiver of Cheque)',
    'Cheque Number',
    'Cheque Date',
    'Cheque Amount',
    'Reason for Dishonor',
  ],
  'Consumer Complaint': [
    'Complainant Name',
    'Complainant Address',
    'Opposite Party Name',
    'Opposite Party Address',
    'Details of Goods/Service',
    'Defect/Deficiency in Service',
    'Relief Claimed',
  ],
  'Divorce Petition': [
    'Petitioner Name',
    'Respondent Name',
    'Date of Marriage',
    'Place of Marriage',
    'Grounds for Divorce',
  ],
  'Durable Power of Attorney': [
    'Principal Name',
    'Principal Address',
    'Agent Name',
    'Agent Address',
    'Powers Granted',
    'Effective Date',
  ],
  'Franchise Agreement': [
    'Franchisor Name',
    'Franchisee Name',
    'Franchise Territory',
    'Franchise Fee',
    'Royalty Percentage',
    'Term of Agreement',
  ],
  'Gift Deed': [
    'Donor Name',
    'Donor Address',
    'Donee Name',
    'Donee Address',
    'Property Description',
    'Date of Gift',
  ],
  'Indemnity Bond': [
    'Indemnifier Name',
    'Indemnity Holder Name',
    'Contract/Agreement Reference',
    'Indemnified Amount',
    'Purpose of Indemnity',
  ],
  'Joint Venture Agreement': [
    'Party A Name',
    'Party B Name',
    'Venture Name',
    'Purpose of Venture',
    'Initial Capital Contribution by Party A',
    'Initial Capital Contribution by Party B',
  ],
  'Lease Agreement': [
    'Lessor (Landlord) Name',
    'Lessee (Tenant) Name',
    'Leased Property Address',
    'Lease Term (in years)',
    'Rent Amount per Month',
    'Security Deposit',
  ],
  'Legal Notice': [
    'Sender Name',
    'Sender Address',
    'Recipient Name',
    'Recipient Address',
    'Subject',
    'Detailed Grievance',
    'Relief Sought',
  ],
  'Living Will': [
    'Declarant Name',
    'Declarant Address',
    'Healthcare Agent Name',
    'End-of-Life Care Wishes',
  ],
  'Mortgage Deed': [
    'Mortgagor (Borrower) Name',
    'Mortgagee (Lender) Name',
    'Loan Amount',
    'Property Details for Mortgage',
  ],
  'Non-Disclosure Agreement (NDA)': [
    'Disclosing Party Name',
    'Receiving Party Name',
    'Confidential Information Description',
    'Term of NDA',
  ],
  'Partnership Deed': [
    'Partner 1 Name',
    'Partner 1 Address',
    'Partner 2 Name',
    'Partner 2 Address',
    'Business Name',
    'Business Address',
    'Capital Contribution by Partner 1',
    'Capital Contribution by Partner 2',
    'Profit/Loss Sharing Ratio',
  ],
  'Paternity Acknowledgment': ['Mother\'s Name', 'Father\'s Name', 'Child\'s Name', 'Date of Birth'],
  'Pleading Paper': ['Court Name', 'Case Number', 'Plaintiff Name', 'Defendant Name', 'Pleading Title'],
  'Power of Attorney': [
    'Principal Name',
    'Principal Address',
    'Agent (Attorney-in-Fact) Name',
    'Agent Address',
    'Powers Granted',
    'Date of Execution',
    'Place of Execution',
  ],
  'Prenuptial Agreement': ['Party 1 Name', 'Party 2 Name', 'Effective Date', 'Asset Division Terms'],
  'Promissory Note': ['Maker (Borrower) Name', 'Payee (Lender) Name', 'Principal Amount', 'Interest Rate', 'Maturity Date'],
  'Property Sale Agreement': ['Seller Name', 'Buyer Name', 'Property Address', 'Sale Price', 'Closing Date'],
  'Relinquishment Deed': ['Releasor Name', 'Releasee Name', 'Description of Relinquished Property', 'Consideration (if any)'],
  'Rent Agreement': [
    'Landlord Name',
    'Landlord Address',
    'Tenant Name',
    'Tenant Address',
    'Property Address',
    'Rent Amount',
    'Lease Term (in months)',
    'Security Deposit',
  ],
  'Sale Deed': [
    'Vendor Name',
    'Vendor Address',
    'Vendee Name',
    'Vendee Address',
    'Property Description',
    'Sale Amount',
    'Witness 1 Name',
    'Witness 2 Name',
  ],
  'Service Level Agreement (SLA)': ['Service Provider', 'Client', 'Description of Services', 'Performance Metrics', 'Uptime Guarantee'],
  'Settlement Agreement': ['Party A Name', 'Party B Name', 'Settlement Amount', 'Terms of Settlement'],
  'Special Power of Attorney': ['Principal Name', 'Agent Name', 'Specific Powers Granted', 'Purpose'],
  'Trust Deed': ['Settlor Name', 'Trustee Name', 'Beneficiary Name', 'Trust Property Details'],
  'Will': [
    'Testator Name',
    'Testator Address',
    'Executor Name',
    'Executor Address',
    'Beneficiary Name',
    'Beneficiary Relationship',
    'Asset Details',
  ],
  'Adoption Deed': [
    'Adoptive Father\'s Name',
    'Adoptive Mother\'s Name',
    'Biological Father\'s Name',
    'Biological Mother\'s Name',
    'Child\'s Name',
    'Date of Adoption',
  ],
  'Arbitration Agreement': [
    'Party 1 Name',
    'Party 2 Name',
    'Subject of Dispute',
    'Seat of Arbitration',
  ],
  'Assignment Deed': [
    'Assignor Name',
    'Assignee Name',
    'Asset/Right to be Assigned',
    'Consideration Amount',
  ],
  'Co-founder\'s Agreement': [
    'Founder 1 Name',
    'Founder 2 Name',
    'Company Name',
    'Equity Split',
    'Roles and Responsibilities',
  ],
  'Consultancy Agreement': [
    'Consultant Name',
    'Client Name',
    'Services to be Provided',
    'Consultation Fee',
  ],
  'Contract for Services': [
    'Service Provider Name',
    'Client Name',
    'Description of Services',
    'Payment Terms',
  ],
  'Copyright License Agreement': ['Licensor Name', 'Licensee Name', 'Licensed Work', 'Territory', 'License Fee'],
  'Debt Settlement Agreement': ['Debtor Name', 'Creditor Name', 'Original Debt Amount', 'Settlement Amount'],
  'Employee Offer Letter': ['Company Name', 'Candidate Name', 'Job Title', 'Salary', 'Start Date'],
  'End-User License Agreement (EULA)': ['Software Name', 'License Grant Terms', 'Restrictions on Use'],
  'Escrow Agreement': ['Party A', 'Party B', 'Escrow Agent', 'Assets in Escrow', 'Release Conditions'],
  'Founders\'s Agreement': ['Founder 1 Name', 'Founder 2 Name', 'Vesting Schedule', 'IP Assignment'],
  'Freelancer Agreement': ['Client Name', 'Freelancer Name', 'Scope of Work', 'Payment Rate'],
  'Hypothecation Deed': ['Borrower Name', 'Lender Name', 'Asset being Hypothecated', 'Loan Amount'],
  'Intellectual Property (IP) Assignment Agreement': ['Assignor', 'Assignee', 'IP being Assigned'],
  'Internship Agreement': ['Company Name', 'Intern Name', 'Duration', 'Stipend (if any)'],
  'Loan Agreement': [
    'Lender Name',
    'Borrower Name',
    'Loan Amount',
    'Interest Rate',
    'Repayment Schedule',
  ],
  'Memorandum of Understanding (MoU)': [
    'Party 1 Name',
    'Party 2 Name',
    'Purpose of MoU',
    'Key Responsibilities of Parties',
  ],
  'Music License Agreement': ['Licensor', 'Licensee', 'Track Title', 'Usage Rights'],
  'No Objection Certificate (NOC)': [
    'Issuer Name',
    'Recipient Name',
    'Purpose of NOC',
    'Details of Property/Item',
  ],
  'Partition Deed': ['Co-owner 1 Name', 'Co-owner 2 Name', 'Property to be Partitioned', 'Share of Each Co-owner'],
  'Postnuptial Agreement': ['Spouse 1 Name', 'Spouse 2 Name', 'Asset and Liability Division'],
  'Release Agreement': ['Releasing Party', 'Released Party', 'Description of Claim being Released'],
  'Rent Receipt': ['Tenant Name', 'Landlord Name', 'Rent Amount', 'Rental Period'],
  'Resignation Letter': ['Employee Name', 'Company Name', 'Last Working Day', 'Reason for Leaving'],
  'Share Purchase Agreement': ['Seller Name', 'Buyer Name', 'Number of Shares', 'Price per Share'],
  'Shareholders\'s Agreement': ['Shareholder 1 Name', 'Shareholder 2 Name', 'Company Name', 'Voting Rights'],
  'Software Development Agreement': ['Client Name', 'Developer Name', 'Project Scope', 'Milestones and Payment'],
  'Software License Agreement': ['Licensor Name', 'Licensee Name', 'Software Name', 'License Term'],
  'Sponsorship Agreement': ['Sponsor Name', 'Event/Entity being Sponsored', 'Sponsorship Amount', 'Sponsor Benefits'],
  'Surrender of Tenancy': ['Tenant Name', 'Landlord Name', 'Property Address', 'Date of Surrender'],
  'Term Sheet': ['Company Name', 'Investor Name', 'Investment Amount', 'Valuation'],
  'Terms of Service': ['Service Name/Website Name', 'Effective Date', 'User Obligations'],
  'Trademark License Agreement': ['Licensor', 'Licensee', 'Trademark', 'Territory of Use'],
  'Vehicle Lease Agreement': ['Lessor', 'Lessee', 'Vehicle Make and Model', 'Lease Term', 'Monthly Payment'],
  'Vendor Agreement': ['Vendor Name', 'Client Name', 'Goods/Services to be Provided', 'Payment Terms'],
  'Website Privacy Policy': [
    'Website URL',
    'Types of Data Collected',
    'Purpose of Data Collection',
    'Data Storage and Security Measures',
  ],
  'Website Terms and Conditions': [
    'Website URL',
    'User Responsibilities',
    'Disclaimers',
    'Governing Law',
  ]
};
